from_latest_tag = true
ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = [ "bump set {{version}} -p 'chore(version):' -m 'v{{version}}'" ]
post_bump_hooks = [ "rake release" ]
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "lxi_rb"
owner = "robcarruthers"
authors = [
  { signature = "Rob Carruthers", username = "robcarruthers" }
]

[bump_profiles]

[packages]
