from_latest_tag = true
ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = [ { command = "bump set {{version}}", message = "Bumping gem from {{latest}} to {{version}}" } ]
post_bump_hooks = [ { command = "rake release", message = "Releasing gem {{version}}" } ]
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "lxi_rb"
owner = "robcarruthers"
authors = [
  { signature = "Rob Carruthers", username = "robcarruthers" }
]

[bump_profiles]

[packages]
